baseURL = "https://cloudnativegeo.org"
title = "Cloud-Native Geospatial Foundation"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
relativeURLs = true

[params]
  description = "Expanding access to geospatial data with commonly-used data formats and HTTP."
  copyright = "Copyright © 2023 Radiant Earth Foundation"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    pageref = "/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    pageref = "/about"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    pageref = "/blog"
    weight = 20

  [[menu.main]]
    identifier = "donate"
    name = "donate"
    title = "donate"
    pageref = "/donate"
    weight = 30


[permalinks]
  blog = "blog/:year/:month/:slug/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
